### ISSUE TITLE
Report max memory used.

### ISSUE THREAD

**Issue by skanskan** [h2oai/db-benchmark#204] opened 2021-05-09 16:18 UTC
Hello.

I think it would be very interesting to report not only the time but also the maximum memory needed by the different solutions.

**Comment by jangorecki** [comment] 2021-05-09 20:33
Hi, this is a duplicate of #9. It is on the roadmap but currently there is a lot of maintenance related tasks.

**Closed by jangorecki** 2021-05-09 20:33 UTC
