### ISSUE TITLE
Add benchark with missings

### ISSUE THREAD

**Issue by skanskan** [h2oai/db-benchmark#54] opened 2018-12-05 19:19 UTC
It would also be interesting to see how fast are all these tools when the data contains missings.

**Comment by jangorecki** [comment] 2018-12-06 05:07
Thanks for feedback, we have that tests done. The problem is that pandas does not support NAs in columns you are grouping by. It requires to replace NAs with sentinel value (like `-1`). And just this would require to have 2 different benchmark script for pandas, and that would obviously complicate whole workflow which is agnostic to presence of NAs.
We will definitely add that case, but I still hope pandas will manage to resolve that issue for 0.24.0 and we will not have to maintain another exceptions. Related issue in pandas repo: https://github.com/pandas-dev/pandas/issues/3729 requested in 2013.
Closing this issue as duplicate of #40.

**Comment by jangorecki** [comment] 2020-12-13 16:01
Re-opening as the linked issue asked about groupby task only.
I am now working on groupby. I will keep this issue open for join task.

**Comment by jangorecki** [comment] 2021-01-04 08:48
It has been added and report has been refreshed.

**Closed by jangorecki** 2021-01-04 08:48 UTC
